apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
#type: Opaque means that from kubernetes's point of view the contents of this Secret is unstructured.
#It can contain arbitrary key-value pairs.
type: Opaque
data:
  # Output of echo -n 'Redhat1449' | base64 # this secret needs to be refernced in my deployment files
  db-password: ZGJwYXNzd29yZDEx