apiVersion: v1
kind: Service
metadata:
  name: front-end-loadbalancer
  labels:
    app: front-twitter-loadbalancer
spec: # load balance will have 3 things type,selector,ports what kind of loadbalncer ,selector what is the application ot has to send traffic to
  type: LoadBalancer # or ClusterIp for internal loadbalcning and NodePort
  selector:
    app: front-end-pod # which pod it will send the incoming traffic to
  ports:
    - name: http #name of port
      port: 80  # service port
      targetPort: 80 # containerport where it will send the traffic to