apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-helloworld-rs
  labels:
    app: my-helloworld
spec: # replicas selector{matchLabels},template{metadata-{labels}}
  replicas: 3
  selector:
    matchLabels:
      app: my-helloworld
  template:
    metadata:
      labels:
        app: my-helloworld
    spec:
      containers:
        - name: my-helloworld-app
          image: stacksimplify/kube-helloworld:1.0.0



describe a replicaset 
kubectl describe rs <name-of-rs>